import com.sun.java.swing.plaf.windows.resources.windows;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JRootPane;
/**
 *
 * @author Ramayanti
 */
public class halUtama extends javax.swing.JFrame {
    jurnalUM jurnalUmum;
    jurnalPenjualan varJurnalPenjualan;
    jurnalPembelian varJurnalPembelian;
    jurnalKhususI varJurnalKhusus1;
    bukuBesar varBukuBesar;
    laporanKeuangan varLaporanKeuangan;
    JFrame frame;
    appAkuntan appAkuntansi;
    laporanPenjualan varLaporanPenjualan;
    
    saldoAwal varSaldoAwal;
    /**
     * Creates new form halUtama
     */
    public halUtama() {
        initComponents();
        iconFrame();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        appAkuntansi = new appAkuntan();
        jurnalUmum = new jurnalUM();
        varJurnalPenjualan = new jurnalPenjualan();
        varJurnalPembelian = new jurnalPembelian();
        varJurnalKhusus1 = new jurnalKhususI();
        varBukuBesar = new bukuBesar();
        varLaporanKeuangan = new laporanKeuangan();
        varLaporanPenjualan = new laporanPenjualan();
        varSaldoAwal = new saldoAwal();
//        
//        this.setUndecorated(true);
//        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
//        frame.setDefaultCloseOperation(0);
//        
    }
    public void iconFrame(){
        ImageIcon imgIc = new ImageIcon("ic_rate_18dp");
        this.setIconImage(imgIc.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneBlack = new gambarJDesktop();
        jMenuBarTop = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemJPenjualan = new javax.swing.JMenuItem();
        jMenuItemJPembelian = new javax.swing.JMenuItem();
        jMenJurnalUmum = new javax.swing.JMenu();
        jMenuItemSaldoAwal = new javax.swing.JMenuItem();
        jMenuItemJK = new javax.swing.JMenuItem();
        jMenuItemBukuBesar = new javax.swing.JMenuItem();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuItemKeuangan = new javax.swing.JMenuItem();
        jMenuItemPenjualan = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jDesktopPaneBlackLayout = new javax.swing.GroupLayout(jDesktopPaneBlack);
        jDesktopPaneBlack.setLayout(jDesktopPaneBlackLayout);
        jDesktopPaneBlackLayout.setHorizontalGroup(
            jDesktopPaneBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jDesktopPaneBlackLayout.setVerticalGroup(
            jDesktopPaneBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPaneBlack);

        jMenuBarTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBarTop.setToolTipText("");

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_store_black_48dp.png"))); // NOI18N
        jMenu2.setText("MENU    ");
        jMenu2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_shopping_cart_black_36dp.png"))); // NOI18N
        jMenu1.setText("Transaksi");
        jMenu1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N

        jMenuItemJPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_monetization_on_black_18dp.png"))); // NOI18N
        jMenuItemJPenjualan.setText("Penerimaan & Penjualan");
        jMenuItemJPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemJPenjualan);

        jMenuItemJPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_add_shopping_cart_black_18dp.png"))); // NOI18N
        jMenuItemJPembelian.setText("Pengeluaran & Pembelian");
        jMenuItemJPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJPembelianActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemJPembelian);

        jMenu2.add(jMenu1);

        jMenJurnalUmum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenJurnalUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_rate_review_black_36dp.png"))); // NOI18N
        jMenJurnalUmum.setText("Jurnal ");
        jMenJurnalUmum.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jMenJurnalUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenJurnalUmumActionPerformed(evt);
            }
        });

        jMenuItemSaldoAwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_assignment_black_18dp.png"))); // NOI18N
        jMenuItemSaldoAwal.setText("Saldo Awal");
        jMenuItemSaldoAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaldoAwalActionPerformed(evt);
            }
        });
        jMenJurnalUmum.add(jMenuItemSaldoAwal);

        jMenuItemJK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_assignment_black_18dp.png"))); // NOI18N
        jMenuItemJK.setText("Jurnal Khusus");
        jMenuItemJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJKActionPerformed(evt);
            }
        });
        jMenJurnalUmum.add(jMenuItemJK);

        jMenuItemBukuBesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_assignment_black_18dp.png"))); // NOI18N
        jMenuItemBukuBesar.setText("Buku Besar");
        jMenuItemBukuBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBukuBesarActionPerformed(evt);
            }
        });
        jMenJurnalUmum.add(jMenuItemBukuBesar);

        jMenu2.add(jMenJurnalUmum);

        jMenuLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_description_48dp (4).png"))); // NOI18N
        jMenuLaporan.setText("Laporan ");
        jMenuLaporan.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N

        jMenuItemKeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_monetization_on_black_18dp.png"))); // NOI18N
        jMenuItemKeuangan.setText("Keuangan");
        jMenuItemKeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeuanganActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuItemKeuangan);

        jMenuItemPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_monetization_on_black_18dp.png"))); // NOI18N
        jMenuItemPenjualan.setText("Penjualan");
        jMenuItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPenjualanActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuItemPenjualan);

        jMenu2.add(jMenuLaporan);

        jMenuBarTop.add(jMenu2);

        jMenuHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_help_48dp.png"))); // NOI18N
        jMenuHelp.setText("HELP    ");
        jMenuHelp.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelpMouseClicked(evt);
            }
        });
        jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpActionPerformed(evt);
            }
        });
        jMenuBarTop.add(jMenuHelp);

        setJMenuBar(jMenuBarTop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenJurnalUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenJurnalUmumActionPerformed
//        jurnalUmum.setVisible(true);
//        jDesktopPaneBlack.add(jurnalUmum);
//        jurnalUmum.moveToFront();
//        System.out.println("workkk!!");
    }//GEN-LAST:event_jMenJurnalUmumActionPerformed

    private void jMenuItemBukuBesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBukuBesarActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varBukuBesar.setVisible(true);
                jDesktopPaneBlack.add(varBukuBesar);
                varBukuBesar.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varBukuBesar.getSize();
                varBukuBesar.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varBukuBesar.setVisible(true);
                jDesktopPaneBlack.add(varBukuBesar);
                varBukuBesar.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varBukuBesar.getSize();
                varBukuBesar.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemJPenjualanAction ");
        }
//old-lama-jFrame
////        appAkuntansi.setVisible(true);
//        try {
//            appAkuntan test = new appAkuntan();
//            JFrame jf = new  JFrame();
//            jf.setResizable(false);
//            if(jDesktopPaneBlack.getAllFrames().length == 0){
//                jf.setContentPane(test.getContentPane());
//                jf.pack();
//                jf.setLocationRelativeTo(getRootPane());
//                jf.setVisible(true);
//                jDesktopPaneBlack.add(test);
////                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
////                jf.setLocation(dim.width/2-jf.getSize().width/2, dim.height/2-jf.getSize().height/2);
//            }
//            else{
//                jDesktopPaneBlack.remove(0);
//                jf.setContentPane(test.getContentPane());
//                jf.pack();
//                jf.setLocationRelativeTo(getRootPane());
//                jf.setVisible(true);
//                jDesktopPaneBlack.add(test);
//            }
//            
//        } catch (Exception e) {
//            System.out.println("error di jMenuBukuBesar");
//        }
    }//GEN-LAST:event_jMenuItemBukuBesarActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuHelpActionPerformed

    private void jMenuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelpMouseClicked
        JOptionPane.showMessageDialog(null, "No help today bro, get back cari CUEUE dulu om\n\n- Lagi sibuk -");
    }//GEN-LAST:event_jMenuHelpMouseClicked

    private void jMenuItemJPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJPenjualanActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varJurnalPenjualan.setVisible(true);
                jDesktopPaneBlack.add(varJurnalPenjualan);
                varJurnalPenjualan.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varJurnalPenjualan.getSize();
                varJurnalPenjualan.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varJurnalPenjualan.setVisible(true);
                jDesktopPaneBlack.add(varJurnalPenjualan);
                varJurnalPenjualan.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varJurnalPenjualan.getSize();
                varJurnalPenjualan.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemJPenjualanAction ");
        }
    }//GEN-LAST:event_jMenuItemJPenjualanActionPerformed

    private void jMenuItemJPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJPembelianActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varJurnalPembelian.setVisible(true);
                jDesktopPaneBlack.add(varJurnalPembelian);
                varJurnalPembelian.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varJurnalPembelian.getSize();
                varJurnalPembelian.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varJurnalPembelian.setVisible(true);
                jDesktopPaneBlack.add(varJurnalPembelian);
                varJurnalPembelian.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varJurnalPembelian.getSize();
                varJurnalPembelian.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemJPembelianAction ");
        }
    }//GEN-LAST:event_jMenuItemJPembelianActionPerformed

    private void jMenuItemJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJKActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varJurnalKhusus1.setVisible(true);
                jDesktopPaneBlack.add(varJurnalKhusus1);
                varJurnalKhusus1.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varJurnalKhusus1.getSize();
                varJurnalKhusus1.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varJurnalKhusus1.setVisible(true);
                jDesktopPaneBlack.add(varJurnalKhusus1);
                varJurnalKhusus1.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varJurnalKhusus1.getSize();
                varJurnalKhusus1.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemJKAction ");
        }       
    }//GEN-LAST:event_jMenuItemJKActionPerformed

    private void jMenuItemKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeuanganActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varLaporanKeuangan.setVisible(true);
                jDesktopPaneBlack.add(varLaporanKeuangan);
                varLaporanKeuangan.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varLaporanKeuangan.getSize();
                varLaporanKeuangan.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varLaporanKeuangan.setVisible(true);
                jDesktopPaneBlack.add(varLaporanKeuangan);
                varLaporanKeuangan.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varLaporanKeuangan.getSize();
                varLaporanKeuangan.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemKeuanganAction ");
        }
    }//GEN-LAST:event_jMenuItemKeuanganActionPerformed

    private void jMenuItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPenjualanActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varLaporanPenjualan.setVisible(true);
                jDesktopPaneBlack.add(varLaporanPenjualan);
                varLaporanPenjualan.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varLaporanPenjualan.getSize();
                varLaporanPenjualan.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varLaporanPenjualan.setVisible(true);
                jDesktopPaneBlack.add(varLaporanPenjualan);
                varLaporanPenjualan.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varLaporanPenjualan.getSize();
                varLaporanPenjualan.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemPenjualanAction ");
        }
    }//GEN-LAST:event_jMenuItemPenjualanActionPerformed

    private void jMenuItemSaldoAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaldoAwalActionPerformed
        try {
            if(jDesktopPaneBlack.getAllFrames().length == 0){
                varSaldoAwal.setVisible(true);
                jDesktopPaneBlack.add(varSaldoAwal);
                varSaldoAwal.moveToFront();
                System.out.println("workkk!!");
//                set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varSaldoAwal.getSize();
                varSaldoAwal.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
            }
            else{
                jDesktopPaneBlack.remove(0);
                varSaldoAwal.setVisible(true);
                jDesktopPaneBlack.add(varSaldoAwal);
                varSaldoAwal.moveToFront();
                System.out.println("workkk!!");
                //set ditengah
                Dimension dimensi = jDesktopPaneBlack.getSize();
                Dimension jInternalSize = varSaldoAwal.getSize();
                varSaldoAwal.setLocation((dimensi.width - jInternalSize.width)/2,(dimensi.height-jInternalSize.height)/2);
                revalidate();
                repaint();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error di jMenuItemSaldoAwalAction ");
        }
    }//GEN-LAST:event_jMenuItemSaldoAwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halUtama().setVisible(true);
//                new dbKonek();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneBlack;
    private javax.swing.JMenu jMenJurnalUmum;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarTop;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemBukuBesar;
    private javax.swing.JMenuItem jMenuItemJK;
    private javax.swing.JMenuItem jMenuItemJPembelian;
    private javax.swing.JMenuItem jMenuItemJPenjualan;
    private javax.swing.JMenuItem jMenuItemKeuangan;
    private javax.swing.JMenuItem jMenuItemPenjualan;
    private javax.swing.JMenuItem jMenuItemSaldoAwal;
    private javax.swing.JMenu jMenuLaporan;
    // End of variables declaration//GEN-END:variables
}
